import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/components/ReduxProvider";
import { store } from "@/hooks/store";

const geistSans = Geist({
  variable: "--font-inter",
  subsets: ["latin"],
});

const theme = store.getState().theme.theme;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme={theme}>
      <body
        className={`${geistSans.variable} antialiased default`}
        style={{ backgroundColor: "var(--background)", color: "var(--foreground)",
            backgroundImage: "url('/bg-1.png')",
            backgroundSize: "cover",
            backgroundPosition: "center",
            minHeight: "100vh"
        }}
      >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
